### PR TITLE
Fix syntax warnings due to comparison of literals using is.

### LINKED ISSUE #31: Syntax warning due to comparison of literals using is in Python 3.8
```
find . -iname '*.py'  | xargs -P 4 -I{} python -Walways -m py_compile {}

./googlecloudprofiler/client.py:167: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(self._profilers) is 0:
```

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #31

### CODE REVIEW

**Comment by kalyanac** [comment]
Thanks for the PR. The repo is not currently setup for accepting PRs. We will shortly push code with this change.

**Comment by tirkarthi** [comment]
Thanks for the update.

**Comment by mgrdcm** [comment]
@kalyanac This is still happening, and showing up even more in Python 3.8.

**Comment by kalyanac** [comment]
We'll have a PR merged today.

**Comment by tirkarthi** [comment]
Closing as this was fixed. Thanks.

**Pull request closed without merging**
